"use client";
import { useState, useMemo } from "react";
import type { DCFModel } from "@/types/model";

function calcIVPS(model: DCFModel, scenario: "bear" | "base" | "bull"): number {
  const a = model.assumptions;
  const hist = model.historicalPeriods;
  if (!hist.length) return 0;
  const growthKey = `revenueGrowth${scenario.charAt(0).toUpperCase() + scenario.slice(1)}` as keyof typeof a;
  const ebitMargin = scenario === "bear" ? a.ebitMarginBear : scenario === "bull" ? a.ebitMarginBull : a.ebitMarginBase;
  const wacc = scenario === "bear" ? a.waccBear : scenario === "bull" ? a.waccBull : a.waccBase;
  const growthRates = a[growthKey] as number[];
  let rev = hist[0].revenue / 1e6;
  const fcfs: number[] = [];
  const pvFcfs: number[] = [];
  for (let yr = 1; yr <= a.projectionYears; yr++) {
    rev *= (1 + growthRates[yr - 1]);
    const ebit = rev * ebitMargin;
    const nopat = ebit * (1 - a.taxRate);
    const fcf = nopat + rev * a.depreciationPct - rev * a.capexPct;
    fcfs.push(fcf);
    pvFcfs.push(fcf / Math.pow(1 + wacc, yr - 0.5));
  }
  if (wacc <= a.terminalGrowthRate) return 0;
  const tv = (fcfs[a.projectionYears - 1] * (1 + a.terminalGrowthRate)) / (wacc - a.terminalGrowthRate);
  const pvTV = tv / Math.pow(1 + wacc, a.projectionYears);
  const ev = pvFcfs.reduce((s, v) => s + v, 0) + pvTV;
  return (ev - a.netDebt - a.minorityInterest) / a.sharesOutstanding;
}

function MarkdownSection({ text }: { text: string }) {
  const sections = text.split(/^## /m).filter(Boolean);
  return (
    <div className="space-y-6">
      {sections.map((section, i) => {
        const [heading, ...lines] = section.split("\n");
        const body = lines.join("\n").trim();
        return (
          <div key={i} className="space-y-2">
            <h3 className="text-sm font-bold text-gray-900 uppercase tracking-wide border-b border-gray-200 pb-2">
              {heading.replace(/^##\s*/, "")}
            </h3>
            <div className="text-sm text-gray-700 leading-relaxed whitespace-pre-line">{body}</div>
          </div>
        );
      })}
    </div>
  );
}

export function InvestmentMemo({ model }: { model: DCFModel }) {
  const [loading, setLoading] = useState(false);
  const [memo, setMemo] = useState("");
  const [error, setError] = useState("");

  const { bearIVPS, baseIVPS, bullIVPS } = useMemo(() => ({
    bearIVPS: calcIVPS(model, "bear"),
    baseIVPS: calcIVPS(model, "base"),
    bullIVPS: calcIVPS(model, "bull"),
  }), [model]);

  const currentPrice = model.currentPrice ?? 0;
  const upside = currentPrice > 0 ? ((baseIVPS - currentPrice) / currentPrice * 100).toFixed(1) : "N/A";
  const rec = baseIVPS > currentPrice * 1.1 ? "BUY" : baseIVPS < currentPrice * 0.9 ? "SELL" : "HOLD";
  const recColor = rec === "BUY" ? "bg-green-700" : rec === "SELL" ? "bg-red-700" : "bg-yellow-600";

  async function generate() {
    setLoading(true);
    setError("");
    setMemo("");
    try {
      const res = await fetch("/api/ai-explain", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          mode: "memo",
          ticker: model.ticker,
          companyName: model.companyName,
          sector: model.sector,
          industry: model.industry,
          currentPrice,
          bearIVPS, baseIVPS, bullIVPS,
          assumptions: model.assumptions,
          historicalPeriods: model.historicalPeriods,
        }),
      });
      const data = await res.json() as { result?: string; error?: string };
      if (data.error) { setError(data.error); return; }
      setMemo(data.result ?? "");
    } catch { setError("AI request failed"); }
    finally { setLoading(false); }
  }

  function print() {
    const w = window.open("", "_blank");
    if (!w) return;
    w.document.write(`<!DOCTYPE html><html><head><title>${model.ticker} Investment Memo</title>
<style>body{font-family:Calibri,sans-serif;max-width:800px;margin:40px auto;padding:0 40px;font-size:13px;line-height:1.6;color:#111}
h1{font-size:18px;border-bottom:2px solid #1a3a5c;padding-bottom:8px}
h3{font-size:12px;text-transform:uppercase;letter-spacing:0.05em;color:#1a3a5c;border-bottom:1px solid #ddd;padding-bottom:4px;margin-top:20px}
p{margin:6px 0}.badge{display:inline-block;padding:2px 10px;border-radius:4px;font-weight:bold;font-size:14px}
.buy{background:#166534;color:white}.sell{background:#991b1b;color:white}.hold{background:#854d0e;color:white}
</style></head><body>
<h1>${model.companyName} (${model.ticker}) — Investment Memorandum</h1>
<p><span class="badge ${rec.toLowerCase()}">${rec}</span> &nbsp; Base IVPS: $${baseIVPS.toFixed(2)} &nbsp; Upside: ${upside}% &nbsp; Current: $${currentPrice.toFixed(2)}</p>
<pre style="white-space:pre-wrap;font-family:inherit">${memo}</pre>
<p style="margin-top:40px;font-size:10px;color:#888">Generated by BOE DCF Platform · For internal use only · Not for distribution</p>
</body></html>`);
    w.document.close();
    w.print();
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="rounded-2xl overflow-hidden border border-gray-200 shadow-sm">
        <div className="bg-gray-900 px-6 py-5 flex items-center justify-between">
          <div>
            <h2 className="text-white font-bold text-base uppercase tracking-wide">One-Click Investment Memo</h2>
            <p className="text-gray-400 text-sm mt-1">{model.companyName} ({model.ticker}) · {model.sector}</p>
          </div>
          <span className={`${recColor} text-white font-bold text-xl px-5 py-2 rounded-lg`}>{rec}</span>
        </div>
        <div className="bg-white px-6 py-4 flex items-center gap-6 border-b border-gray-200">
          <div className="text-center">
            <p className="text-xs text-gray-400 uppercase tracking-wide">Bear IVPS</p>
            <p className="font-mono font-bold text-red-700">${bearIVPS.toFixed(2)}</p>
          </div>
          <div className="text-center">
            <p className="text-xs text-gray-400 uppercase tracking-wide">Base IVPS</p>
            <p className="font-mono font-bold text-blue-700">${baseIVPS.toFixed(2)}</p>
          </div>
          <div className="text-center">
            <p className="text-xs text-gray-400 uppercase tracking-wide">Bull IVPS</p>
            <p className="font-mono font-bold text-green-700">${bullIVPS.toFixed(2)}</p>
          </div>
          <div className="text-center">
            <p className="text-xs text-gray-400 uppercase tracking-wide">Current Price</p>
            <p className="font-mono font-bold text-gray-800">${currentPrice.toFixed(2)}</p>
          </div>
          <div className="text-center">
            <p className="text-xs text-gray-400 uppercase tracking-wide">Implied Upside</p>
            <p className={`font-mono font-bold ${parseFloat(upside) >= 0 ? "text-green-700" : "text-red-700"}`}>{upside}%</p>
          </div>
          <div className="ml-auto flex gap-2">
            <button onClick={generate} disabled={loading}
              className="bg-gray-900 text-white px-5 py-2.5 rounded-xl text-sm font-medium hover:bg-gray-700 disabled:opacity-40 transition-colors">
              {loading ? "Generating…" : memo ? "↻ Regenerate" : "✨ Generate Memo"}
            </button>
            {memo && (
              <button onClick={print} className="border border-gray-300 text-gray-700 px-4 py-2.5 rounded-xl text-sm hover:bg-gray-50 transition-colors">
                Print
              </button>
            )}
          </div>
        </div>
      </div>

      {error && <div className="text-red-600 bg-red-50 border border-red-200 rounded-xl px-4 py-3 text-sm">{error}</div>}

      {loading && (
        <div className="flex items-center justify-center py-16">
          <div className="text-center space-y-3">
            <div className="w-8 h-8 border-2 border-blue-600 border-t-transparent rounded-full animate-spin mx-auto" />
            <p className="text-sm text-gray-500">DeepSeek is writing your investment memo…</p>
          </div>
        </div>
      )}

      {memo && !loading && (
        <div className="bg-white rounded-2xl border border-gray-200 shadow-sm px-8 py-6">
          {/* Memo header */}
          <div className="border-b-2 border-gray-900 pb-4 mb-6">
            <p className="text-xs text-gray-400 uppercase tracking-widest">BOE Group — Equity Research</p>
            <h1 className="text-xl font-bold text-gray-900 mt-1">{model.companyName} ({model.ticker})</h1>
            <p className="text-sm text-gray-500 mt-1">Investment Memorandum · {model.sector} · {model.industry}</p>
            <div className="flex items-center gap-4 mt-3">
              <span className={`${recColor} text-white text-xs font-bold px-3 py-1 rounded`}>{rec}</span>
              <span className="text-sm text-gray-600">Base Target: <strong>${baseIVPS.toFixed(2)}</strong></span>
              <span className="text-sm text-gray-600">Upside: <strong className={parseFloat(upside) >= 0 ? "text-green-700" : "text-red-700"}>{upside}%</strong></span>
              <span className="text-xs text-gray-400 ml-auto">AI-Generated · DeepSeek · For Internal Use Only</span>
            </div>
          </div>
          <MarkdownSection text={memo} />
          <div className="mt-8 pt-4 border-t border-gray-200 text-xs text-gray-400">
            This memo was generated by BOE DCF Platform using DeepSeek AI. It is for internal research purposes only and does not constitute investment advice.
            Model date: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}.
          </div>
        </div>
      )}
    </div>
  );
}
